### ISSUE TITLE
Who should be allowed to create repositories?

### ISSUE THREAD

**Issue by skyem123** [Nightfall/Nightfall#2]
I was looking through the team settings, and I've noticed that I cannot make a team that can create repositories, so that means that we either have to let everyone in @Nightfall/contributors to be able to make repositories (we **do** trust them), and if we don't trust someone not to make stupid repositories, we can make them an outside collaborator.

What do you think, @Nightfall/operators?

**Comment by skyem123** [comment]
Also, should we have a team that has admin access to some repos, so @Achati can manage the SRails repo?

**Comment by RX14** [comment]
Do you have the new github teams thing? I thought it had more granular permissions.

**Comment by skyem123** [comment]
It doesn't seem to allow me to create a group that can create repos...

**Comment by RX14** [comment]
But have you got the new group system?

**Comment by skyem123** [comment]
Yes, I can tell due to the "rename the owners group" notice.

**Comment by NikkyAI** [comment]
Yeahh Having full control over SRails would be useful,  if you can work out the group stuff

**Comment by skyem123** [comment]
@Achati, you now have a secret team called @Nightfall/achati-dev, that has admin access to the SRails repo.

Still not sure what to do about creating repositories, though...

**Comment by marysaka** [comment]
Maybe we should make a bot with the Owner access to create them...

**Comment by skyem123** [comment]
That's possible, but then there's also the question of how the people would administrate the repos that they have created...

**Comment by skyem123** [comment]
There doesn't seem to be a way to let people create their own repositories and only have admin access over the repos they create, as far as I can tell (I might be misunderstanding the settings...)

**Comment by RX14** [comment]
You can totally do per-repo settings. You could even do that with the old permissions.

**Comment by skyem123** [comment]
Gah... this is too confusing... okay... so...

If I allowed collaborators make repositories, would it give the people that made a repo have admin access to that repo?

**Comment by skyem123** [comment]
Oh, and @Achati, I deleted the @Nightfall/achati-dev group, if you want it back I just yell at me. :P

**Comment by skyem123** [comment]
Well... I think it's decided.
