### ISSUE TITLE
Make an "archive" where I can store old code and repos that a want to delete, but still have some useful code.

### ISSUE THREAD

**Issue by skyem123** [Nightfall/Nightfall#4]
Stuff like [node-mcmuch-auth](../../node-mcmuch-auth) should be removed because it's worthless, but I don't want it gone forever...

**Comment by NikkyAI** [comment]
well you could zip the thing and put it on a shared dropbox to reupload it later.. but you could also mark it as inactive or so..

**Comment by RX14** [comment]
Just don't delete repos, they are free.

**Comment by skyem123** [comment]
you can mark repos as inactive?

**Comment by NikkyAI** [comment]
add [inactive] or [discontinued] to the name
no idea if there is a action

**Comment by RX14** [comment]
No, leave a note in the readme saying it's not maintained. It's simple and what everyone else does.

**Comment by skyem123** [comment]
fine...
